<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\ForgotPasswordRequest;
use App\Http\Requests\LoginRequest;
use App\Http\Requests\RegisterRequest;
use App\Http\Requests\ResetPasswordRequest;
use App\Http\Resources\UserResource;
use App\Models\User;
use App\Services\CartService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Password;
use Illuminate\Validation\ValidationException;

class AuthController extends Controller
{
    public function __construct(private CartService $carts)
    {
    }

    public function register(RegisterRequest $request)
    {
        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => $request->password,
            'role' => User::ROLE_CUSTOMER,
            'newsletter' => $request->boolean('newsletter'),
        ]);

        if (!$user->hasVerifiedEmail()) {
            $user->sendEmailVerificationNotification();
        }

        $this->carts->mergeGuestIntoUser($user, $request->header('X-Session-Id'));

        $token = $user->createToken('api')->plainTextToken;

        return response()->json([
            'data' => [
                'token' => $token,
                'user' => new UserResource($user),
            ],
        ], 201);
    }

    public function login(LoginRequest $request)
    {
        if (!Auth::guard('web')->validate([
            'email' => $request->email,
            'password' => $request->password,
        ])) {
            throw ValidationException::withMessages([
                'email' => ['Invalid credentials.'],
            ]);
        }

        $user = User::where('email', $request->email)->firstOrFail();

        $this->carts->mergeGuestIntoUser($user, $request->header('X-Session-Id'));

        $token = $user->createToken('api')->plainTextToken;

        return response()->json([
            'data' => [
                'token' => $token,
                'user' => new UserResource($user),
            ],
        ]);
    }

    public function logout(Request $request)
    {
        $request->user()->currentAccessToken()->delete();

        return response()->json(['data' => ['message' => 'Logged out successfully.']]);
    }

    public function me(Request $request)
    {
        return new UserResource($request->user());
    }

    /**
     * Verify a user's email address. Guarded by the `signed` middleware;
     * the signed URL is generated by the VerifyEmail notification.
     */
    public function verify(Request $request)
    {
        $user = User::findOrFail((int) $request->route('id'));

        if (!hash_equals(sha1($user->getEmailForVerification()), (string) $request->route('hash'))) {
            abort(403, 'Invalid email verification link.');
        }

        if (!$user->hasVerifiedEmail()) {
            $user->markEmailAsVerified();
            $message = 'Email verified successfully.';
        } else {
            $message = 'Your email is already verified.';
        }

        if ($request->expectsJson()) {
            return response()->json(['data' => ['message' => $message]]);
        }

        $url = rtrim((string) config('app.frontend_url'), '/').'/auth/verify-email?verified=1';

        return redirect()->away($url);
    }

    /**
     * Resend the email verification notification to the authenticated user.
     */
    public function sendVerificationEmail(Request $request)
    {
        $user = $request->user();

        if ($user->hasVerifiedEmail()) {
            return response()->json(['data' => ['message' => 'Your email is already verified.']]);
        }

        $user->sendEmailVerificationNotification();

        return response()->json(['data' => ['message' => 'Verification email sent.']]);
    }

    public function forgotPassword(ForgotPasswordRequest $request)
    {
        Password::broker('users')->sendResetLink($request->only('email'));

        return response()->json([
            'data' => ['message' => 'If an account exists for that email, a password reset link has been sent.'],
        ]);
    }

    public function resetPassword(ResetPasswordRequest $request)
    {
        $status = Password::broker('users')->reset(
            $request->only('email', 'password', 'password_confirmation', 'token'),
            function (User $user, string $password) {
                $user->forceFill(['password' => $password])->save();
                $user->tokens()->delete();
            }
        );

        if ($status !== Password::PASSWORD_RESET) {
            throw ValidationException::withMessages([
                'email' => [$status],
            ]);
        }

        return response()->json([
            'data' => ['message' => 'Password reset successfully.'],
        ]);
    }
}
